# Generated by Django 3.2.9 on 2022-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('CAL', 'Calgary'), ('VAN', 'Vancouver')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('CAN', 'Canada'), ('USA', 'United States')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(choices=[('AB', 'Alberta'), ('ON', 'Ontario')], default=None, max_length=50, null=True),
        ),
    ]
