# Generated by Django 3.2.9 on 2022-07-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220720_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='city_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country_name',
            new_name='country',
        ),
    ]
