# Generated by Django 3.2.9 on 2022-07-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
