# Generated by Django 3.2.9 on 2022-07-22 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220722_0249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProvinceState',
            new_name='Stateprovince',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='provinceState',
            new_name='stateprovince',
        ),
        migrations.RemoveField(
            model_name='city',
            name='provinceState',
        ),
        migrations.AddField(
            model_name='city',
            name='Stateprovince',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stateprovince', to='users.stateprovince'),
        ),
    ]
