# Generated by Django 3.2.9 on 2022-07-22 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220722_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='stateprovince',
            new_name='stateProvince',
        ),
        migrations.RemoveField(
            model_name='city',
            name='Stateprovince',
        ),
        migrations.AddField(
            model_name='city',
            name='stateProvince',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stateProvince', to='users.stateprovince'),
        ),
    ]
