# Generated by Django 3.2.9 on 2022-07-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
