# Generated by Django 3.2.9 on 2022-07-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_cities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
