# Generated by Django 3.2.9 on 2022-07-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': False},
        ),
    ]
