# Generated by Django 3.2.9 on 2022-07-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='users_userprofile',
        ),
    ]
