# Generated by Django 3.2.9 on 2022-07-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
