# Generated by Django 3.2.9 on 2022-07-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakehighscore',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
