# Generated by Django 3.2.9 on 2022-07-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0002_snakehighscore_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snakehighscore',
            name='description',
        ),
    ]
