# Generated by Django 3.2.9 on 2022-07-15 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snake', '0005_alter_snakehighscore_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakehighscore',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
