# Generated by Django 3.2.9 on 2022-07-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0006_snakehighscore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snakehighscore',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='snakehighscore',
            name='user',
        ),
        migrations.AddField(
            model_name='snakehighscore',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
