# Generated by Django 3.2.9 on 2022-07-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0010_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
