# Generated by Django 3.2.9 on 2022-07-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0011_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snakehighscore',
            old_name='province',
            new_name='stateProvince',
        ),
    ]
