# Generated by Django 3.2.9 on 2022-07-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0014_alter_snakehighscore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snakehighscore',
            name='user',
        ),
    ]
