# Generated by Django 3.2.9 on 2022-07-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220725_1352'),
        ('snake', '0016_snakehighscore_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakehighscore',
            name='userProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
