# Generated by Django 3.2.9 on 2022-07-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0017_alter_snakehighscore_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snakehighscore',
            name='userProfile',
        ),
    ]
