# Generated by Django 3.2.9 on 2022-07-29 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0019_snakehighscore_next_allowed_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakehighscore',
            name='next_allowed_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 16, 57, 35, 420240)),
        ),
    ]
