# Generated by Django 3.2.9 on 2022-08-01 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0021_auto_20220730_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakehighscore',
            name='next_allowed_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 1, 10, 45, 41, 380924), null=True),
        ),
    ]
