# Generated by Django 3.2.9 on 2022-08-01 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0022_alter_snakehighscore_next_allowed_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakehighscore',
            name='time_ten_minutes',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 1, 18, 51, 15, 471134), null=True),
        ),
        migrations.AlterField(
            model_name='snakehighscore',
            name='next_allowed_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 1, 12, 41, 15, 471102), null=True),
        ),
    ]
