# Generated by Django 3.2.9 on 2022-08-01 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0024_auto_20220801_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakehighscore',
            name='next_allowed_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 1, 15, 20, 26, 686519), null=True),
        ),
        migrations.AlterField(
            model_name='snakehighscore',
            name='time_ten_minutes',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 1, 15, 30, 26, 686539), null=True),
        ),
    ]
