# Generated by Django 3.2.9 on 2022-08-02 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0026_auto_20220801_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snakehighscore',
            options={'get_latest_by': ['next_allowed_update', 'time_ten_minutes', 'est_timezone']},
        ),
        migrations.AddField(
            model_name='snakehighscore',
            name='est_timezone',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 15, 10, 27, 632839), null=True),
        ),
        migrations.AlterField(
            model_name='snakehighscore',
            name='next_allowed_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 10, 10, 27, 632797), null=True),
        ),
        migrations.AlterField(
            model_name='snakehighscore',
            name='time_ten_minutes',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 10, 11, 27, 632820), null=True),
        ),
    ]
