# Generated by Django 3.2.9 on 2022-08-02 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0027_auto_20220802_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakehighscore',
            name='est_timezone',
            field=models.DateTimeField(blank=True, default=datetime.timezone, null=True),
        ),
        migrations.AlterField(
            model_name='snakehighscore',
            name='next_allowed_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 11, 21, 45, 6980), null=True),
        ),
        migrations.AlterField(
            model_name='snakehighscore',
            name='time_ten_minutes',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 11, 22, 45, 7001), null=True),
        ),
    ]
