# Generated by Django 3.2.9 on 2022-08-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0029_auto_20220802_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snakehighscore',
            options={'get_latest_by': ['time_now']},
        ),
        migrations.RenameField(
            model_name='snakehighscore',
            old_name='est_timezone',
            new_name='time_now',
        ),
        migrations.RemoveField(
            model_name='snakehighscore',
            name='next_allowed_update',
        ),
        migrations.RemoveField(
            model_name='snakehighscore',
            name='time_ten_minutes',
        ),
    ]
